<?php

/**
 * @file
 * Contains ddhi_rest.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

define('DDHI_MACHINE_NAME_TRANSCRIPT','transcript');

/**
 * Implements hook_help().
 */
function ddhi_rest_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ddhi_rest module.
    case 'help.page.ddhi_rest':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Creates REST endpoints that support the DDHI Oral History Data API') . '</p>';
      return $output;

    default:
  }
}
