<?php

namespace Drupal\ddhi_ingest\Form;

use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;

class DDHIIngestSettingsForm extends ConfigFormBase {

  public function getFormId()
  {
    return 'ddhi_ingest_settings_form';
  }

  public function buildForm(array $form, FormStateInterface $form_state)
  {
    $form = parent::buildForm($form, $form_state);
    $DDHIIngestConfig = $this->config('ddhi_ingest.settings');

    // GitHub Forms

    $form['source_type'] = [
      '#type' => 'select',
      '#title' => $this->t('Source Type'),
      '#description' => $this->t('Select the source location of the DDHI TEI interviews.'),
      '#options' => [
        DDHI_SOURCE_OPTION_GITHUB => $this->t('GitHub Repository'),
        DDHI_SOURCE_OPTION_FILE => $this->t('Uploaded ZIP file (currently inactive)'),
      ],
      '#default_value' => !empty($DDHIIngestConfig->get('source_type')) ? $DDHIIngestConfig->get('source_type') : DDHI_SOURCE_OPTION_GITHUB,
    ];

    $form['source_type_github'] = [
      '#type' => 'fieldset',
      '#title' => $this->t('Default GitHub Repository Settings'),
      '#description' => $this->t('Retrieve DDHI interviews from GitHub repository'),
    ];

    $form['source_type_github']['github_account'] = [
      '#type' => 'textfield',
      '#title' => $this->t('DDHI TEI Repository Account'),
      '#default_value' => !empty($DDHIIngestConfig->get('github_account')) ? $DDHIIngestConfig->get('github_account') : 'Dartmouth-Digital-History-Initiative',
      '#description' => $this->t('The user/account name associated with the repository.'),
    ];

    $form['source_type_github']['github_repository'] = [
      '#type' => 'textfield',
      '#title' => $this->t('DDHI TEI Repository Name'),
      '#default_value' => !empty($DDHIIngestConfig->get('github_repository')) ? $DDHIIngestConfig->get('github_repository') : 'TEI-Encoding',
      '#description' => $this->t('Name of the repository containing the DDHI TEI Interviews in DDHI File Layout Level 1 format.'),
    ];

    $form['source_type_github']['github_branch'] = [
      '#type' => 'textfield',
      '#title' => $this->t('DDHI TEI Branch Name'),
      '#default_value' => !empty($DDHIIngestConfig->get('github_branch')) ? $DDHIIngestConfig->get('github_branch') : 'master',
      '#description' => $this->t('The repository branch to retrieve interviews from.'),
    ];

    return $form;
  }

  public function validateForm(array &$form, FormStateInterface $form_state)
  {
    parent::validateForm($form, $form_state); // TODO: Change the autogenerated stub
  }

  public function submitForm(array &$form, FormStateInterface $form_state)
  {
    $DDHIIngestConfig = $this->config('ddhi_ingest.settings');
    $DDHIIngestConfig->set('source_type',$form_state->getValue('source_type'));
    $DDHIIngestConfig->set('github_account',$form_state->getValue('github_account'));
    $DDHIIngestConfig->set('github_repository',$form_state->getValue('github_repository'));
    $DDHIIngestConfig->set('github_branch',$form_state->getValue('github_branch'));
    $DDHIIngestConfig->save();

    return parent::submitForm($form, $form_state);
  }

  public function getEditableConfigNames()
  {
    return [
      'ddhi_ingest.settings'
    ];
  }
}
